apiVersion: v1
kind: Pod
metadata:
  name: spark
spec:
  containers:
  - name: spark
    volumeMounts:
      - mountPath: "/spark-app"
        name: properties
        readOnly: true      
    imagePullPolicy: IfNotPresent 
    image:  <YOUR_IMAGE_NAME>
    command: ["/bin/sh", "-c"]
    args:
    - /opt/spark/bin/spark-submit --properties-file /spark-app/secrets.txt --class Main local:///app/sparkPractice-assembly-0.1.0-SNAPSHOT.jar
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Never
  volumes:
    - name: properties
      secret:
        secretName: <SECRET_NAME>






