apiVersion: v1
kind: Pod
metadata:
  name: spark2-test
spec:
  containers:
  - name: spark
    image:  lulkaval/spark:latest
    command: ["/bin/sh", "-c"]
    args:
    - spark-submit  --master local[3] \
       --packages "com.amazonaws:aws-java-sdk:1.11.46,com.ibm.stocator:stocator:1.1.4,com.ibm.db2:jcc:11.5.7.0" \
       --conf spark.jars.ivy=/tmp/.ivy \
       <CONFIGS> \
       --class Main sparkpractice_2.12-0.1.0-SNAPSHOT.jar
    ports:
    - containerPort: 80
      protocol: TCP






