apiVersion: v1
kind: Pod
metadata:
  name: spark
spec:
  containers:
  - name: spark
    volumeMounts:
      - mountPath: "/spark-app"
        name: all-properties
        readOnly: true      
    imagePullPolicy: IfNotPresent 
    image:  lulkaval/fat_spark_3_2_1
    command: ["/bin/sh", "-c"]
    args:
    - /opt/spark/bin/spark-submit --properties-file /spark-app/properties --class Main local:///app/sparkPractice-assembly-0.1.0-SNAPSHOT.jar
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Never
  volumes:
    - name: all-properties
      secret:
        secretName: all-properties






