apiVersion: v1
kind: Pod
metadata:
  name: spark
spec:
  containers:
  - name: spark   
    volumeMounts:
      - mountPath: "/spark-app"
        name: conf
        readOnly: true  
    imagePullPolicy: IfNotPresent 
    image: <YOUR_IMAGE_NAME>
    envFrom:
       - secretRef:
           name: storage-secrets
       - secretRef:
           name: database-secrets
    command: ["/bin/sh", "-c"]
    args:
    - /opt/spark/bin/spark-submit --properties-file /spark-app/database-storage.yaml --conf spark.access.key=$spark_access_key --conf spark.secret.key=$spark_secret_key --conf spark.endpoint=$spark_endpoint --conf spark.source.url=$spark_source_url --conf spark.source.username=$spark_source_username --conf spark.source.password=$spark_source_password --class Main local:///app/sparkPractice-assembly-0.1.0-SNAPSHOT.jar
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Never
  volumes:
    - name: conf 
      configMap:
        name: <CONFIG_MAP_NAME>
 











