apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
spec:
  selector:
    matchLabels:
      app: spark
  replicas: 1
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: <YOUR_IMAGE_NAME>
        ports:
        - containerPort: 80
          protocol: TCP