apiVersion: v1
kind: Pod
metadata:
  name: spark-k8s
spec:
  containers:
  - name: spark
    volumeMounts:
      - mountPath: "/spark-app"
        name: <SECRET_NAME>
        readOnly: true      
    imagePullPolicy: IfNotPresent 
    image:  <YOUR_IMAGE_NAME>
    command: ["/bin/sh", "-c"]
    args:
    - /opt/spark/bin/spark-submit --properties-file /spark-app/secrets --deploy-mode cluster --conf spark.kubernetes.container.image=<YOUR_IMAGE_NAME> --class Main local:///app/sparkPractice-assembly-0.1.0-SNAPSHOT.jar  
    ports:
    - containerPort: 80
      protocol: TCP
  restartPolicy: Never
  volumes:
    - name: <SECRET_NAME>
      secret:
        secretName: <SECRET_NAME>

